name: GUI Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'game_launcher.py'
      - 'tests/test_game_launcher.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'game_launcher.py'
      - 'tests/test_game_launcher.py'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.9, "3.10"]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        pip install -e .
    
    - name: Run GUI tests
      run: |
        pytest tests/test_game_launcher.py -v 